export const BIRTHDAY_NOTIFICATION_CHANNEL_ID = "customer-birthdays";
export const BIRTHDAY_NOTIFICATION_IDENTIFIER_PREFIX = "birthday-";
export const BIRTHDAY_NOTIFICATION_DEFAULT_HOUR = 9;
export const BIRTHDAY_NOTIFICATION_DEFAULT_MINUTE = 0;
