export enum NotificationErrorCode {
  PUSH_TOKEN_REGISTER_FAILED = "PUSH_TOKEN_REGISTER_FAILED",
  PUSH_TOKEN_REMOVE_FAILED = "PUSH_TOKEN_REMOVE_FAILED",
  SETTINGS_FETCH_FAILED = "SETTINGS_FETCH_FAILED",
  SETTINGS_UPDATE_FAILED = "SETTINGS_UPDATE_FAILED",
  INVALID_PUSH_TOKEN = "INVALID_PUSH_TOKEN",
}
