export enum ProductErrorCode {
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_CREATE_FAILED = "PRODUCT_CREATE_FAILED",
  PRODUCT_FETCH_FAILED = "PRODUCT_FETCH_FAILED",
  PRODUCT_UPDATE_FAILED = "PRODUCT_UPDATE_FAILED",
  PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED",
}
